-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bills
(
    billid serial NOT NULL,
    billfrom character varying COLLATE pg_catalog."default",
    "billType" character varying COLLATE pg_catalog."default",
    "amountDue" double precision,
    "dueDate" date,
    "isPaid" boolean,
    "paidInFull" boolean,
    "amountPaid" double precision,
    "datePaid" date,
    "paidBy" character varying COLLATE pg_catalog."default",
    CONSTRAINT bills_pkey PRIMARY KEY (billid)
);
END;